import { useState } from "react";
import { CheckIcon, XIcon, DashIcon, SparkleIcon } from "./Icons.jsx";

function VoteBadge({ position }) {
  const p = (position || "").toLowerCase();
  if (p === "yes") {
    return (
      <span className="vote-badge vote-yes" title="Voted Yes">
        <CheckIcon /> <span>Yes</span>
      </span>
    );
  }
  if (p === "no") {
    return (
      <span className="vote-badge vote-no" title="Voted No">
        <XIcon /> <span>No</span>
      </span>
    );
  }
  return (
    <span className="vote-badge vote-abstain" title="Did not vote / Present">
      <DashIcon /> <span>{position || "Not Voting"}</span>
    </span>
  );
}

export default function VoteItem({ vote, repName }) {
  const [expanded, setExpanded] = useState(false);
  const [explanation, setExplanation] = useState("");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");

  async function handleExplain() {
    if (explanation || loading) {
      setExpanded((e) => !e);
      return;
    }
    setExpanded(true);
    setLoading(true);
    setError("");
    try {
      const res = await fetch("/api/explain", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          bill_title: vote.bill_title,
          bill_description: vote.bill_description,
          vote_position: vote.vote_position,
          rep_name: repName,
        }),
      });
      if (!res.ok) {
        const body = await res.json().catch(() => ({}));
        throw new Error(body.detail || `Request failed (${res.status})`);
      }
      const data = await res.json();
      setExplanation(data.explanation);
    } catch (e) {
      setError(e.message || "Could not load explanation.");
    } finally {
      setLoading(false);
    }
  }

  return (
    <li className="vote-item">
      <div className="vote-row">
        <div className="vote-main">
          <div className="vote-title">{vote.bill_title}</div>
          <div className="vote-date">{vote.date}</div>
        </div>
        <VoteBadge position={vote.vote_position} />
      </div>
      <button
        className={`explain-btn ${expanded ? "active" : ""}`}
        onClick={handleExplain}
        disabled={loading}
      >
        <SparkleIcon />
        <span>
          {loading
            ? "Asking Claude..."
            : explanation
              ? expanded
                ? "Hide explanation"
                : "Show explanation"
              : "Explain in plain language"}
        </span>
      </button>
      {expanded && (
        <div className="explanation-box">
          {error && <div className="explanation-error">{error}</div>}
          {!error && loading && (
            <div className="explanation-loading">
              Generating a plain-language summary...
            </div>
          )}
          {!error && !loading && explanation && (
            <>
              <div className="explanation-label">
                Plain-language explanation
              </div>
              <p className="explanation-text">{explanation}</p>
              <div className="explanation-footer">
                Generated by Claude. Nonpartisan, factual.
              </div>
            </>
          )}
        </div>
      )}
    </li>
  );
}
